// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr7v8yTBa0UQMqi4xbo4HsnF96m5WsGeg',
    appId: '1:977377121603:web:7fe93e37027289502c0bf6',
    messagingSenderId: '977377121603',
    projectId: 'eatapp-77ca2',
    authDomain: 'eatapp-77ca2.firebaseapp.com',
    storageBucket: 'eatapp-77ca2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoB_YBHyFkGzYdMPh5u3YWa0TWQFrx3Cg',
    appId: '1:977377121603:android:f1f2b0e44560c4de2c0bf6',
    messagingSenderId: '977377121603',
    projectId: 'eatapp-77ca2',
    storageBucket: 'eatapp-77ca2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATO4yMcdChcr9q1s1gAETR1XkGoPGe2DM',
    appId: '1:977377121603:ios:0a74714c5f8e89bd2c0bf6',
    messagingSenderId: '977377121603',
    projectId: 'eatapp-77ca2',
    storageBucket: 'eatapp-77ca2.appspot.com',
    iosClientId: '977377121603-prvgeogagde2ig5ml1b9ck9ruuvi69om.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATO4yMcdChcr9q1s1gAETR1XkGoPGe2DM',
    appId: '1:977377121603:ios:0a74714c5f8e89bd2c0bf6',
    messagingSenderId: '977377121603',
    projectId: 'eatapp-77ca2',
    storageBucket: 'eatapp-77ca2.appspot.com',
    iosClientId: '977377121603-prvgeogagde2ig5ml1b9ck9ruuvi69om.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
